services:
    roh_stack_manager.command.preview_stack:
        class: ROH\Bundle\StackManagerBundle\Command\PreviewStackCommand
        arguments:
            - @roh_stack_manager.mapper.stack_config
        tags:
            - { name: console.command }

    roh_stack_manager.command.create_stack:
        class: ROH\Bundle\StackManagerBundle\Command\CreateStackCommand
        arguments:
            - @roh_stack_manager.mapper.stack_config
            - @roh_stack_manager.service.stack_manager
        tags:
            - { name: console.command }

    roh_stack_manager.command.compare_stack:
        class: ROH\Bundle\StackManagerBundle\Command\CompareStackCommand
        arguments:
            - @roh_stack_manager.mapper.stack_api
            - @roh_stack_manager.mapper.stack_config
            - @roh_stack_manager.service.stack_comparison
        tags:
            - { name: console.command }

    roh_stack_manager.command.update_stack:
        class: ROH\Bundle\StackManagerBundle\Command\UpdateStackCommand
        arguments:
            - @roh_stack_manager.mapper.stack_api
            - @roh_stack_manager.mapper.stack_config
            - @roh_stack_manager.service.stack_manager
            - @roh_stack_manager.service.stack_watcher
        tags:
            - { name: console.command }

    roh_stack_manager.command.delete_stack:
        class: ROH\Bundle\StackManagerBundle\Command\DeleteStackCommand
        arguments:
            - @roh_stack_manager.mapper.stack_api
            - @roh_stack_manager.service.stack_manager
        tags:
            - { name: console.command }

    roh_stack_manager.command.list_stacks:
        class: ROH\Bundle\StackManagerBundle\Command\ListStacksCommand
        arguments:
            - @roh_stack_manager.mapper.stack_api
        tags:
            - { name: console.command }

    roh_stack_manager.command.check_stacks:
        class: ROH\Bundle\StackManagerBundle\Command\CheckStacksCommand
        arguments:
            - @roh_stack_manager.mapper.stack_api
            - @roh_stack_manager.mapper.stack_config
        tags:
            - { name: console.command }

    roh_stack_manager.command.list_templates:
        class: ROH\Bundle\StackManagerBundle\Command\ListTemplatesCommand
        arguments:
            - %roh_stack_manager.defaults%
            - %roh_stack_manager.environments%
            - %roh_stack_manager.scaling_profiles%
        tags:
            - { name: console.command }

    roh_stack_manager.mapper.stack_api:
        class: ROH\Bundle\StackManagerBundle\Mapper\StackApiMapper
        arguments:
            - @roh_stack_manager.service.template_expansion
            - @aws.cloudformation

    roh_stack_manager.mapper.stack_config:
        class: ROH\Bundle\StackManagerBundle\Mapper\StackConfigMapper
        arguments:
            - @templating
            - %roh_stack_manager.defaults%
            - %roh_stack_manager.environments%
            - %roh_stack_manager.scaling_profiles%

    roh_stack_manager.mapper.stack_event_api:
        class: ROH\Bundle\StackManagerBundle\Mapper\StackEventApiMapper
        arguments:
            - @aws.cloudformation

    roh_stack_manager.service.stack_manager:
        class: ROH\Bundle\StackManagerBundle\Service\StackManagerService
        arguments:
            - @roh_stack_manager.service.template_squashing
            - @aws.cloudformation

    roh_stack_manager.service.stack_watcher:
        class: ROH\Bundle\StackManagerBundle\Service\StackWatcherService
        arguments:
            - @roh_stack_manager.mapper.stack_event_api

    roh_stack_manager.service.stack_comparison:
        class: ROH\Bundle\StackManagerBundle\Service\StackComparisonService

    roh_stack_manager.service.template_squashing:
        class: ROH\Bundle\StackManagerBundle\Service\TemplateSquashingService
        arguments:
            - @aws.s3
            - %aws_template_bucket%

    roh_stack_manager.service.template_expansion:
        class: ROH\Bundle\StackManagerBundle\Service\TemplateExpansionService
        arguments:
            - @buzz
            - @aws.cloudformation

    roh_stack_manager.twig.cidr:
        class:  ROH\Bundle\StackManagerBundle\TwigExtension\CidrTwigExtension
        tags:
            - { name: twig.extension }

    roh_stack_manager.twig.cloudformation:
        class:  ROH\Bundle\StackManagerBundle\TwigExtension\CloudFormationTwigExtension
        arguments:
            - @aws.cloudformation
        tags:
            - { name: twig.extension }

    roh_stack_manager.twig.codedeploy:
        class:  ROH\Bundle\StackManagerBundle\TwigExtension\CodeDeployTwigExtension
        arguments:
            - @aws.codedeploy
        tags:
            - { name: twig.extension }

    roh_stack_manager.twig.ebs:
        class:  ROH\Bundle\StackManagerBundle\TwigExtension\EbsTwigExtension
        arguments:
            - @aws.ec2
        tags:
            - { name: twig.extension }

    roh_stack_manager.twig.ec2:
        class:  ROH\Bundle\StackManagerBundle\TwigExtension\Ec2TwigExtension
        arguments:
            - @aws.ec2
        tags:
            - { name: twig.extension }

    roh_stack_manager.twig.rds:
        class:  ROH\Bundle\StackManagerBundle\TwigExtension\RdsTwigExtension
        arguments:
            - @aws.rds
            - @aws.iam
        tags:
            - { name: twig.extension }
