imports:
    - { resource: parameters.ini }

framework:
    templating:
        engines: ['twig']
    # Required for the uri_signer service, which is always enabled.
    secret: secret
    # Required for the templating engine, although we don't need routing.  This
    # file doesn't actually exist or need to exist for our purposes.
    router:
        resource: "%kernel.root_dir%/config/routing.yml"

aws:
    region: %aws_region%
    credentials:
        key: %aws_access_key_id%
        secret: %aws_secret_key%
    CloudFormation:
        version: '2010-05-15'
    Ec2:
        version: '2015-10-01'
    Iam:
        version: '2010-05-08'
        region: us-east-1
    Rds:
        version: '2014-10-31'
    S3:
        version: '2006-03-01'

roh_temporal_scaling:
    calendar_sources: {}
